### PR TITLE
compression of floating elements on a web page

### PR DESCRIPTION
**Pull request by aristides1000**
integration request from Feature branch to master branch

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

## Hello team,

**Great job on your project. Your attention to details is remarkable.**

**Please make the following changes so your project can be approved.**

1). **As you scroll down, the page content should disappear behind the fixed navbar and not display in front of it.**

nav_clone

2). **The page is missing a log in button at the rightmost side of the navbar. Also, the account dropdown, on the navbar, doesn't appear in the original [page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0).**

3). **All social media icons should be links.**

4). **The button labelled 'Read 615 comments' above the most popular section should be a link.**

5). **In the 'More in Space and Astronomy' and 'Editor's pick' sections, increase the font size for the dates and the small captions directly below the right side of every image.**

6). **Increase font size for the text in the `footer_bottom` class and `footer_right` class.**

7). **The new york logo in the footer should be a link.**

8). **The Theory of Inflation section doesn't have a title.**

9). **In the readme file, the live demo and issues page links do not work.**

10). **Your pull request should have a meaningful title and summary of what you have achieved or done in your project. Use this [guideline](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).**

**Note: .stylelintrc.json and .hintrc should not be added in the .gitignore file.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

**Comment by aristides1000** [comment]
I made all requested changes for your review

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

#### Hello, @aristides1000 and @AlejandroNo4, 

You've done a great job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [ ] Your elements are not centered on the page, kindly fix this. 
center


- [ ] Like the previous TSE requested, kindly remove .stylelintrc.json and .hintrc from the .gitignore file.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by aristides1000** [comment]
Thank you very much for your comments, the relevant changes have already been made

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

#### Hello, @aristides1000 and @AlejandroNo4,

You are almost there!
Let's make this one change, and we will be done.

- [ ] Note: One of the requirements of this project is that it contains centered text and images, Please see the screenshot below. Try to center the image properly.
center

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by aristides1000** [comment]
muchas gracias por sus observaciones, ya se hicieron los cambios pertinentes

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team! Great job working on the previously required changes!

## Required Changes
### [Mandatory] :red_circle: 

- [x] Issues link takes to another project issue page.

- [x] Project doesn't have a title in HTML file
image

- [x] Element not centered
image

- [x] Unaligned elemenst
image

- [x] Remove the ```cursor: pointer``` and use an anchor tag for all links. 

- [x] The NYT logo should be a link in the navbar and the footer

- [x] The titles and images of the articles should be links.

- [x] Elements in footer are not looking as original
image

### [OPTIONAL]  :large_blue_circle: 

- [ ] In the HTML file break lines if they are greater than 80 characters long. this improves readability.

- [ ] Keep the code DRY in the CSS.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by aristides1000** [comment]
Thank you very much for your comments, the relevant changes have already been made

**Review by jubaan — APPROVED** [review]
# Status: Approved :tada: :tada: :tada:

## Great work team! :clap: :clap: :clap: 

You've done all previously required changes. You may now merge to master!

## See you at the top :rocket: !!

**Pull request merged**
